### ISSUE TITLE
Support OS 10.10 / Yosemite

### ISSUE THREAD

**Issue by mimecuvalo** [dchest/webp-quicklook#2] opened 2014-10-21 05:50 UTC
Currently busted in Yosemite unfortunately. :-/

**Comment by dchest** [comment] 2014-10-21 07:28
Looks like recompiling with newer Xcode solves the crash. Could you please try the new release? https://github.com/dchest/webp-quicklook/releases/tag/v2.2

(You may need to restart Mac after replacing qlgenerator).

**Comment by mimecuvalo** [comment] 2014-10-22 05:17
Yeah, before contacting you I had tried myself recompiling with Xcode but to no avail.  
Trying your latest release doesn't seem to fix it as far as I can tell :-/
I had tried restarting and running `qlmanage -r` as well.  Not sure what's up.

**Comment by dchest** [comment] 2014-10-22 07:09
Strange, it works for me. Could you please post the output this command (and whether it shows the preview):

```
qlmanage -g "/Users/dchest/Library/QuickLook/WebP.qlgenerator" -c "com.google.webp" -p ~/Desktop/picture.webp
```

(Replace paths with yours, of course)

also this:

```
qlmanage -m | grep webp
```

**Comment by mimecuvalo** [comment] 2014-10-26 06:49
Here's the output:

```
⚡️  qlmanage -g "/Users/mime/Library/QuickLook/WebP.qlgenerator" -c "com.google.webp" -p ~/test.webp
Testing Quick Look preview with files:
    /Users/mime/test.webp
    - force using content type UTI: com.google.webp
    - force using generator at path: /Users/mime/Library/QuickLook/WebP.qlgenerator
2014-10-25 23:41:37.566 qlmanage[7206:235057] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xc633, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2014-10-25 23:41:37.579 qlmanage[7206:235057] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xc82b, name = 'com.apple.CFPasteboardClient'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2014-10-25 23:41:37.579 qlmanage[7206:235057] Failed to allocate communication port for com.apple.CFPasteboardClient; this is likely due to sandbox restrictions
2014-10-25 23:41:37.596 qlmanage[7206:235057] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xc85f, name = 'com.apple.coredrag'
See /usr/include/servers/bootstrap_defs.h for the error codes.
```

```
qlmanage -m | grep webp
  com.google.webp -> /Users/mime/Library/QuickLook/WebP.qlgenerator (2.2)
  public.webp -> /Users/mime/Library/QuickLook/WebP.qlgenerator (2.2)
```

**Comment by dchest** [comment] 2014-10-26 06:51
Thanks. I have the same output and then it shows the preview. What you get instead? If it doesn't show the preview, could you send me the file you're trying to preview if it's possible? dmitry@codingrobots.com

**Comment by mimecuvalo** [comment] 2014-10-26 15:19
It does show the preview correctly.  It's only in Finder where the preview doesn't show up unfortunately.  Finder looks like this:

![screenshot 2014-10-26 08 16 50](https://cloud.githubusercontent.com/assets/469604/4783349/25d6b4ac-5d23-11e4-9de8-aaaf47b61c28.png)

**Comment by dchest** [comment] 2014-10-26 17:03
@mimecuvalo hmm, maybe some other QuickLook generator kicks in instead of this one (although qlmanage shows the right one...)? Or maybe there's something with this particular .webp file? Could you try if this one works: https://www.gstatic.com/webp/gallery3/1_webp_ll.webp

**Comment by mimecuvalo** [comment] 2014-10-27 16:24
Yeah, I tried with the test image and other images and on a different machine.  Didn't work as well :-/

**Comment by dchest** [comment] 2014-10-27 16:29
I'm out of ideas :( Can't reproduce this, unfortunately.

**Comment by mimecuvalo** [comment] 2014-10-27 16:56
No worries, thanks for checking it out in the first place - I'll dig in some more into the code when I get some time later ;)

**Comment by mimecuvalo** [comment] 2014-12-09 07:44
This seems to be working now - I moved it to /Library instead of my home directory ~/Library  - that was the problem.

**Comment by dchest** [comment] 2014-12-09 09:44
Thanks! Strange that it didn't work in ~/Library.

**Comment by vitorgalvao** [comment] 2014-12-11 22:26
@dchest It’d likely be valuable to keep this open, since the underlying issue hasn’t been resolved.

On [homebrew-cask](https://github.com/caskroom/homebrew-cask) we had an [issue](https://github.com/caskroom/homebrew-cask/issues/6448) open recently pertaining to this, which is how I found this issue.

After some tests I found this issue, whatever the cause, also affects [@emin’s plugin](https://github.com/emin/WebPQuickLook), so maybe you’d be interested in working together on it. So far, every other quicklook plugin I’ve tried seems to be working normally.

**Comment by dchest** [comment] 2014-12-12 09:23
I'm reopening the issue. But I still can't reproduce the bug — it works on my machine (I have WebP.qlgenerator in ~/Library/QuickLook, and I verified that it is really it that shows previews). Can I ask someone who's having this issue to create a new OS X account on their machine and try putting it again in ~/Library/QuickLook for that account (make sure to delete the one in /Library/QuickLook first)?

**Comment by orzFly** [comment] 2015-05-06 13:11
Didn't work after installing from brew-cask as it created a symlink to WebP.qlgenerator in ~/Library/QuickLook. However, I replaced the symlink with the actual bundle and then it got to be working now!

I hope this helps!

**Comment by felixbuenemann** [comment] 2015-07-23 14:22
In my case the quicklook generator in Pixelmator was taking preference (and wasn't working). I disabled it by editing `/Applications/Pixelmator.app/Contents/Library/QuickLook/PixelmatorLook.qlgenerator/Contents/Info.plist` and removing the webp document type.

**Comment by FirePanther** [comment] 2015-10-10 22:11
For me it was pixelmators fault, thank you @felixbuenemann. It even didn't work by moving to /Library. (OSX10.11)

**Comment by zmwangx** [comment] 2016-01-19 21:53
Just so you guys know, I was having the same issue on El Cap due to Pixelmator, and I've emailed bugs@pixelmator.com asking them to unbind `public.webp` from `PixelmatorLook.qlgenerator/Contents/Info.plist`. I also started a support forum thread: http://support.pixelmator.com/viewtopic.php?t=12602.

**Comment by dchest** [comment] 2016-01-19 22:57
Thanks everyone, it looks like it's a Pixelmator bug, so I'm closing this issue. Feel free to comment here if they resolve it.

**Closed as completed by dchest** 2016-01-19 22:57 UTC

**Comment by kentliau** [comment] 2016-07-19 13:19
As of today, Pixelmator (v3.5 Canyon) still hasn't deal with webp problem yet. For anyone encounter the similar problem, a quick workaround is remove `public.webp` extension binding yourself in `/Applications/Pixelmator.app/Contents/Library/QuickLook/PixelmatorLook.qlgenerator/Contents/info.plist`

**Comment by zmwangx** [comment] 2016-07-19 13:21
@kentliau You might want to email bugs@pixelmator.com. The more user complaints, the more likely they're going to take this issue seriously.

**Comment by mattstein** [comment] 2016-07-22 00:42
@felixbuenemann's fix just worked for me as well, thank you. I sent an email to bugs@pixelmator.com as @zmwangx suggested, so hopefully that ticket will get some attention.

**Comment by mattstein** [comment] 2016-07-22 22:58
FWIW I got a fairly quick response from Pixelmator:

> Thanks for getting in touch and giving us a heads up about this – this is still on our radar. :)
